= Brokers can't connect to each other
:toc:

*Instruction:* https://redpanda.com/guides/kafka-tutorial/kafka-without-zookeeper

check settings from here https://zhuanlan.zhihu.com/p/595020396

== Hypothese #1: Broker fails before others start

`Broker1` starts. Tries to connect to others few times, then shutdown.
When `Broker2` started, `Broker1` had already been shutdown.

*Evidence:* the first message "Connection to node could not be established." is at `20:13:20`.
Graceful shutdown in at `20:14:24`. One minute might not be enough to start other brokers.

.tail -f  /opt/kafka/logs/kafkaServer.out
[source, logs]
----
[2023-04-03 20:13:20,632] INFO [RaftManager nodeId=2] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:13:20,634] WARN [RaftManager nodeId=2] Connection to node 1 (kafka1/10.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:13:20,634] INFO [RaftManager nodeId=2] Node 3 disconnected. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:13:20,635] WARN [RaftManager nodeId=2] Connection to node 3 (kafka3/10.0.0.3:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:13:20,704] INFO [RaftManager nodeId=2] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
----

[source, logs]
----
[2023-04-03 20:14:24,017] WARN [RaftManager nodeId=2] Connection to node 1 (kafka1/10.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:14:24,189] INFO [RaftManager nodeId=2] Node 3 disconnected. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:14:24,189] WARN [RaftManager nodeId=2] Connection to node 3 (kafka3/10.0.0.3:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-04-03 20:14:24,323] WARN [RaftManager nodeId=2] Graceful shutdown timed out after 5000ms (org.apache.kafka.raft.KafkaRaftClient)
[2023-04-03 20:14:24,325] ERROR [kafka-raft-io-thread]: Graceful shutdown of RaftClient failed (kafka.raft.KafkaRaftManager$RaftIoThread)
java.util.concurrent.TimeoutException: Timeout expired before graceful shutdown completed
        at org.apache.kafka.raft.KafkaRaftClient$GracefulShutdown.failWithTimeout(KafkaRaftClient.java:2416)
        at org.apache.kafka.raft.KafkaRaftClient.maybeCompleteShutdown(KafkaRaftClient.java:2163)
        at org.apache.kafka.raft.KafkaRaftClient.poll(KafkaRaftClient.java:2230)
        at kafka.raft.KafkaRaftManager$RaftIoThread.doWork(RaftManager.scala:61)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2023-04-03 20:14:24,326] INFO [kafka-raft-io-thread]: Stopped (kafka.raft.KafkaRaftManager$RaftIoThread)
[2023-04-03 20:14:24,326] INFO [kafka-raft-io-thread]: Shutdown completed (kafka.raft.KafkaRaftManager$RaftIoThread)
[2023-04-03 20:14:24,336] INFO [kafka-raft-outbound-request-thread]: Shutting down (kafka.raft.RaftSendThread)
[2023-04-03 20:14:24,337] INFO [kafka-raft-outbound-request-thread]: Stopped (kafka.raft.RaftSendThread)
[2023-04-03 20:14:24,337] INFO [kafka-raft-outbound-request-thread]: Shutdown completed (kafka.raft.RaftSendThread)
----

*Possible fix:* increase wait timeout. Or run all within one minute.

*Result:* Didn't help.

== Hypothese #2: `/etc/hosts` (don't know)

`/etc/hosts` has two IPs for `kafkaN` domain name. Which can affect connecion

*Evidence:*  I see both `(kafka1/10.0.0.1:9092)` and `(kafka1/127.0.0.1:9092)` in logs.

.cat /etc/hosts
----
127.0.0.1       localhost
127.0.1.1       kafka1      vagrant

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.0.0.1        kafka1
10.0.0.2        kafka2
10.0.0.3        kafka3
----

*Possible fix:*
[source, bash]
----
sed -i 's/127.*kafka.*/#&/' /etc/hosts
----

*Result:* Partially helped. No more `(kafka1/127.0.0.1:9092)` in logs, but the problem remains.

== Hypothese #3: Usage of wrong ports (yes).

Broker and controller use the same port. Let's try different.

Try to use `19092` for controllers `9092` for brokers.

----
[2023-04-04 19:43:01,445] ERROR [RaftManager nodeId=2] Unexpected error INCONSISTENT_CLUSTER_ID in VOTE response: InboundResponse(correlationId=855, data=VoteResponseData(errorCode=104, topics=[]), sourceId=1) (org.apache.kafka.raft.KafkaRaftClient)
----

*Result:*  Helped a bit. I started to get a different error.

*Conclusion:* `controller.quorum.voters` and `listeners=CONTROLLER` have to use the same port. It's used for KRaft.
When I fixed it I started getting `INCONSISTENT_CLUSTER_ID`. Google says I have to perform
`kafka-storage.sh format -t ${KAFKA_CLUSTER_ID} -c /opt/kafka/config/kraft/server.properties`. But I did.


== Try one node (success)

I am able to run one node cluster

----
vagrant@kafka1:~$ sudo service kafka status
● kafka.service
   Loaded: loaded (/etc/init.d/kafka; bad; vendor preset: enabled)
   Active: active (running) since Fri 2023-04-07 21:30:40 UTC; 1min 33s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 18701 ExecStart=/etc/init.d/kafka start (code=exited, status=0/SUCCESS)
    Tasks: 89
   Memory: 341.7M
      CPU: 8.125s
   CGroup: /system.slice/kafka.service
           └─19042 java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Xloggc:/opt/kafka/bin/../logs/kafkaS

Apr 07 21:30:40 kafka1 systemd[1]: Starting kafka.service...
Apr 07 21:30:40 kafka1 kafka[18701]: Starting kafka
Apr 07 21:30:40 kafka1 systemd[1]: Started kafka.service.
vagrant@kafka1:~$ kafka-topics.sh --bootstrap-server kafka1:9092 --list

vagrant@kafka1:~$ kafka-topics.sh --create --topic kraft-test --partitions 1 --replication-factor 1 --bootstrap-server kafka1:9092
Created topic kraft-test.
vagrant@kafka1:~$ kafka-topics.sh --bootstrap-server kafka1:9092 --list
kraft-test
----

== Collect info

=== Logs were taken for further investigation
----
$ vagrant scp kafka1:/opt/kafka/logs/ logs/kafka1/
$ vagrant scp kafka2:/opt/kafka/logs/ logs/kafka2/
$ vagrant scp kafka3:/opt/kafka/logs/ logs/kafka3/

$  vagrant scp kafka1:/tmp/kraft-combined-logs/ logs/kafka1/
$  vagrant scp kafka2:/tmp/kraft-combined-logs/ logs/kafka2/
$  vagrant scp kafka3:/tmp/kraft-combined-logs/ logs/kafka3/
----

----

kafka1: KAFKA_CLUSTER_ID=W_QGysAaT26FsylDkCdgnA
kafka2: KAFKA_CLUSTER_ID=SybwVGfhSMua-nqbr9oFxw
kafka3: KAFKA_CLUSTER_ID=1IhHW8KOTOeZKvDOdUqB8Q
----

=== I have access from one node to another

I can connect to port `9092` and `19092`.

----
vagrant@kafka2:~$ ping kafka3
PING kafka3 (10.0.0.3) 56(84) bytes of data.
64 bytes from kafka3 (10.0.0.3): icmp_seq=1 ttl=64 time=0.469 ms
64 bytes from kafka3 (10.0.0.3): icmp_seq=2 ttl=64 time=0.825 ms
64 bytes from kafka3 (10.0.0.3): icmp_seq=3 ttl=64 time=1.04 ms
64 bytes from kafka3 (10.0.0.3): icmp_seq=4 ttl=64 time=0.933 ms
^C
--- kafka3 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 0.469/0.818/1.045/0.215 ms
vagrant@kafka2:~$ nc  kafka3 9092
sdsd
^C
vagrant@kafka2:~$ nc  kafka3 19092
sdsf
vagrant@kafka2:~$ nc  kafka3 19092
ddfdf
vagrant@kafka2:~$ echo $?
0
vagrant@kafka2:~$ nc  kafka3 9093
vagrant@kafka2:~$ echo $?
1
----


== Hypothese #4: I have to use the same 'KAFKA_CLUSTER_ID' for all nodes (yes)

I'm getting `INCONSISTENT_CLUSTER_ID`.

----
[2023-04-08 20:10:47,402] ERROR [RaftManager nodeId=3] Unexpected error INCONSISTENT_CLUSTER_ID in VOTE response: InboundResponse(correlationId=2271, data=VoteResponseData(errorCode=104, topics=[]), sourceId=2) (org.apache.kafka.raft.KafkaRaftClient)
[2023-04-08 20:10:47,403] ERROR [RaftManager nodeId=3] Unexpected error INCONSISTENT_CLUSTER_ID in VOTE response: InboundResponse(correlationId=2270, data=VoteResponseData(errorCode=104, topics=[]), sourceId=1) (org.apache.kafka.raft.KafkaRaftClient)
----


I'll try to set same `KAFKA_CLUSTER_ID` for all three nodes.

[source, bash]
----
KAFKA_CLUSTER_ID='1IhHW8KOTOeZKvDOdUqB8Q'
sudo echo "export KAFKA_CLUSTER_ID=${KAFKA_CLUSTER_ID}" >> /etc/profile

kafka-storage.sh format -t ${KAFKA_CLUSTER_ID} -c /opt/kafka/config/kraft/server.properties
----

*Result:* It works.

----
vagrant@kafka2:~$ kafka-topics.sh --create --topic kraft-test --partitions 3 --replication-factor 3 --bootstrap-server kafka1:9092 kafka2:9092 kafka3:9092
Error while executing topic command : Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 2 broker(s) are registered.
[2023-04-09 13:13:56,390] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 2 broker(s) are registered.
 (kafka.admin.TopicCommand$)
vagrant@kafka2:~$ kafka-topics.sh --create --topic kraft-test --partitions 1 --replication-factor 1 --bootstrap-server kafka1:9092
Created topic kraft-test.
vagrant@kafka2:~$ kafka-topics.sh --bootstrap-server kafka1:9092 --list
kraft-test
vagrant@kafka2:~$ kafka-topics.sh --bootstrap-server kafka3:9092 --list
[2023-04-09 13:18:04,886] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka3/10.0.0.3:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

vagrant@kafka2:~$ kafka-topics.sh --bootstrap-server kafka3:9092 --list
kraft-test
vagrant@kafka2:~$ kafka-topics.sh --create --topic kraft-test2 --partitions 3 --replication-factor 3 --bootstrap-server kafka1:9092 kafka2:9092 kafka3:9092
Created topic kraft-test2.
vagrant@kafka2:~$
----

I got `Unable to replicate the partition 3 time(s):` the first time. I restarted kafka on `kafka3`. Topic `kraft-test2` is replicated for all 3 nodes.

*Conclusion:* I have to use the same `KAFKA_CLUSTER_ID` across all nodes.


== Things to check

=== Use hostname in `listeners`

Current `listeners` property is the following
[source, properties]
----
listeners=PLAINTEXT://:9092,CONTROLLER://:19092
----

Try to use the exact host name
[source, properties]
----
listeners=PLAINTEXT://KAFKA_HOST:9092,CONTROLLER://KAFKA_HOST:9092
----

That's why I have command to replace `KAFKA_HOST` with the actual host name

[source, bash]
----
sed -i 's/KAFKA_HOST/kafka1/g' /opt/kafka/config/kraft/server.properties
----

=== Don't touch `/etc/hosts`

Check if it can work without removing `kafkaN` hostname for `127.0.0.1`

== Kafka commands

[source, bash]
----
kafka-topics.sh --create --topic kraft-test --partitions 3 --replication-factor 3 --bootstrap-server kafka1:9092 kafka2:9092 kafka3:9092
kafka-topics.sh --create --topic kraft-test --partitions 1 --replication-factor 1 --bootstrap-server kafka1:9092
kafka-topics.sh --bootstrap-server kafka1:9092 --list
----